### ISSUE TITLE
Register on a function with argument

### ISSUE THREAD

**Issue by boagg** [kuralabs/multiexit#5]
Hi,

First of all, thank you for making multiexit :)

I was wondering if it was possible to register () 
a function with one argument?

Here is an example :

```
#!/usr/bin/env python
# coding: utf-8

import requests
from multiexit import install, register, unregister, run_exitfuncs
#import multiexit
from os import getpid
import signal



install(signals=(signal.SIGTERM, signal.SIGINT),except_hook=True)
def shared_exit():
    print('Shared exit being called by {} ...'.format(getpid()))

register(shared_exit, shared=True)

@register
def test_get(url):
    response = requests.request("GET", url)
    print(response.status_code)


#global url 
url = 'https://duckduckgo.com/?q=plop&t=h_&ia=definition'

raise Exception('My error!')
```

Currently, this does not seem to work, the agurment 
is not passing to the function and we have this error:

```
Uncaught exception
Traceback (most recent call last):
  File "plop.py", line 27, in <module>
    raise Exception('My error!')
Exception: My error!
Exit function <function test_get at 0x7f64ad61cd08> failed:
Traceback (most recent call last):
  File "/data/[user]/home/.local/share/virtualenvs/venv_test_3.6.9/lib/python3.6/site-packages/multiexit.py", line 75, in run_exitfuncs
    func()
TypeError: test_get() missing 1 required positional argument: 'url'
Shared exit being called by 24182 ...
```

Maybe it's not possible or it's against the ideology of this module ?

I'm happy to contribute a PR if we agree on a solution and you guys think 
it's worth doing.

**Comment by boagg** [comment]
Thank you for your feedback, I close issue
